GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJOYXRhbGlhIFBlcm1hdGEgU2FyaSBCciBCYW5ndW4iLCJlbWFpbCI6ImFiYW5nYnVkaUBnbWFpbC5jb20iLCJpYXQiOjE3NDA0MDIxMTMsImV4cCI6MTc0MDQwMjEzM30.qHvZeS0BXT3wLgoODH6n8SH0N8uuqUuMHT7PH_aD4Vw

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name":"Abdi Jepri Bangun",
    "email":"abdijepri2@gmail.com",
    "password":"1122334455",
    "confPassword":"1122334455"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"abangbudi@gmail.com",
    "password":"1122334455"
}

###
PATCH http://localhost:5000/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsIm5hbWUiOiJOYXRhbGlhIFBlcm1hdGEgU2FyaSBCciBCYW5ndW4iLCJlbWFpbCI6ImFiYW5nYnVkaUBnbWFpbC5jb20iLCJpYXQiOjE3NDA0MDIwMTIsImV4cCI6MTc0MDQwMjAzMn0.QAzpMpmweW4TI4PFulEVCi2Rf0D9ZgWB7hOHNgTyHe4

{
    "name":"Sonya Ginting",
    "email":"abangbudi@gmail.com",
    "password":"1122334455",
    "confPassword":"1122334455"
}



###
DELETE http://localhost:5000/logout